### ISSUE TITLE
I was "just passing through" but...

### ISSUE THREAD

**Issue by Pebaz** [Nickforall/Dioxide#14]
👋 I wanted to say that this is the cleanest JavaScript I have ever seen in my life, well done: https://github.com/Nickforall/Dioxide/blob/master/compiler/Parser.js

If I am not mistaken, I think you made use of Predictive Parsing? (the combination of accept() and expect()). I'm trying to learn how to make languages right now so this is really inspirational!

Great work on the language and good luck! 🙂

**Comment by Nickforall** [comment]
❤️
